### ISSUE TITLE
metric problem

### ISSUE THREAD

**Issue by nicehuster** [AFeng-x/Draw-and-Understand#3]
i evaluated the checkpoint at task of referring object classification on LVIS, the reproduced results is so much higher your official paper, 
your paper(LVIS, sim:87.06, IoU: 62.9 ), the reproduced results(sim:0.927,iou:0.698). Otherwise,  the reproduced results on RefCOCOg is (METEOR:28.8, CIDEr: 384.3),  your paper(METEOR:23.9, CIDEr: 162.5), where is the problem?

**Comment by AFeng-x** [comment]
Hi there,
Actually, your procedure is correct. The ckpt provided in the repo is from a model trained with further improvements, whereas the ckpt used in our paper was from an earlier version that did not undergo extended training.

**Comment by nicehuster** [comment]
it's ok to give some details about the further improvements?

**Comment by TiantZhang** [comment]
> it's ok to give some details about the further improvements?

哈喽，请问你这边复现的结果是直接基于官方公开的权重推理得到的吗？我们尝试推理得到的结果是(sim:95.19,iou:91.62)
