### ISSUE TITLE
Missing mdvp_for_gpt4v_eval dir

### ISSUE THREAD

**Issue by ccxlxy** [AFeng-x/Draw-and-Understand#8]
In MDVP-Bench evaluation，missing mdvp_for_gpt4v_eval dir. 

When executing the following code :
```
cd Region_Level_Captioning/coco-caption
sh eval_cococap.sh
```

I encountered an error message: "FileNotFoundError: [Errno 2] No such file or directory: 'mdvp_for_gpt4v_eval/android_detailed_caption_box_results'".

Look forward to your reply!

**Comment by A113N-W3I** [comment]
It seems that this error is related to the location where the model output is saved. 

Could you provide more specific error information? For example, which line of code in which Python script is causing the error?

**Comment by ccxlxy** [comment]
Thank you for your replay!

The problem has been solved when I modify the code as follows in transfer_to_gpt_format.py
```
if not os.path.exists(f"mdvp_for_gpt4v_eval/{phase}"):
        os.makedirs(f"mdvp_for_gpt4v_eval/{phase}", exist_ok=True)
```
