### ISSUE TITLE
Region Level Captioning Evaluation Code Error

### ISSUE THREAD

**Issue by ccxlxy** [AFeng-x/Draw-and-Understand#9]
In the evaluation of Region Level Captioning, many of the writing styles in the eval/Region_Level_Captioning/pycocoevalcap library file are from Python 2, but when modified to Python 3, the code gets stuck during execution:
![image](https://github.com/user-attachments/assets/5a329f39-2f5d-4ec9-ae8b-6d55ccf7729f)

How should I fix this issue？

**Comment by A113N-W3I** [comment]
Please use the latest code, where I have uploaded pycocoevalcaps. I have already made the necessary modifications, so you can run it in the Python 3 environment. 

Don't forget to modify the `resFile` path in `evalcococap.py`.
